package com.mertaydar.emw.entity;
// Generated 19.Tem.2017 22:36:54 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountId generated by hbm2java
 */
@Embeddable
public class AccountId implements java.io.Serializable {

	private int id;
	private int houseId;

	public AccountId() {
	}

	public AccountId(int id, int houseId) {
       this.id = id;
       this.houseId = houseId;
    }

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name="house_id", nullable=false)
    public int getHouseId() {
        return this.houseId;
    }

	public void setHouseId(int houseId) {
        this.houseId = houseId;
    }

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccountId) ) return false;
		 AccountId castOther = ( AccountId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getHouseId()==castOther.getHouseId());
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getHouseId();
         return result;
   }

}
