package com.mertaydar.emw.entity;
// Generated 19.Tem.2017 22:36:54 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HouseId generated by hbm2java
 */
@Embeddable
public class HouseId implements java.io.Serializable {

	private int id;
	private int userId;

	public HouseId() {
	}

	public HouseId(int id, int userId) {
       this.id = id;
       this.userId = userId;
    }

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }

	public void setUserId(int userId) {
        this.userId = userId;
    }

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HouseId) ) return false;
		 HouseId castOther = ( HouseId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserId()==castOther.getUserId());
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserId();
         return result;
   }

}
