package com.mertaydar.emw.entity;
// Generated 19.Tem.2017 22:36:54 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * House generated by hbm2java
 */
@Entity
@Table(name = "house", catalog = "expense_manager")
public class House implements java.io.Serializable {

	private HouseId id;
	private User user;
	private float total;
	private Set<Account> accounts = new HashSet<Account>(0);

	public House() {
	}

	public House(HouseId id, User user, float total) {
		this.id = id;
		this.user = user;
		this.total = total;
	}

	public House(HouseId id, User user, float total, Set<Account> accounts) {
		this.id = id;
		this.user = user;
		this.total = total;
		this.accounts = accounts;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "user�d", column = @Column(name = "user_id", nullable = false)) })
	public HouseId getId() {
		return this.id;
	}

	public void setId(HouseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "total", nullable = false, precision = 12, scale = 0)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "house")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
